export default {
  plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
  printWidth: 120,
  importOrder: [
    "<TYPES>^(node|bun|deno):",
    "<BUILT_IN_MODULES>",
    "",
    "<TYPES>",
    "<THIRD_PARTY_MODULES>",
    "",
    "<TYPES>^[#](?!components$)",
    "^[#](?!components$)",
    "",
    "<TYPES>^[#](components$)",
    "^[#](components$)",
    "",
    "",
    "<TYPES>^(@nuxt/(ui(-pro)?|image|icon)(/|$))",
    "^(@nuxt/(ui(-pro)?|image|icon)(/|$))",
    "",
    "<TYPES>^[~@]{1,2}/(?!components/)",
    "^[~@]{1,2}/(?!components/)",
    "",
    "<TYPES>^[~@]{1,2}/(components/)",
    "^[~@]{1,2}/(components/)",
    "",
    "<TYPES>^[.]",
    "^[.]",
  ],
  importOrderTypeScriptVersion: "5.0.0",
  tailwindStylesheet: "./app/assets/css/main.css",
};
